% -------------------------------------------------------------------
%  Generated by MATLAB on 23-May-2017 23:53:04
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

raw_data__ = saveVarsMat.raw_data__; % <319999x1 double> ÔªËØÌ«¶à

clear saveVarsMat;
